// src/levels/levelsData.js
// Autogenerated from level JSON files for cross-environment ES module compatibility.

export const LEVELS = [
  {
    "id": 1,
    "title": "LAN Basics",
    "topic": "IP Addressing",
    "description": "Assign IP addresses to two PCs on the same network and verify connectivity with a ping.",
    "ccnaRef": "CCNA ITN: Chapter 8 – Network Layer",
    "sandboxMode": false,
    "objectives": [
      {
        "id": "obj1",
        "desc": "Assign IP 192.168.1.10/24 to PC1"
      },
      {
        "id": "obj2",
        "desc": "Assign IP 192.168.1.20/24 to PC2"
      },
      {
        "id": "obj3",
        "desc": "PC1 can ping PC2"
      }
    ],
    "requirements": [
      {
        "id": "obj1",
        "type": "subnet",
        "desc": "PC1 IP is 192.168.1.10/24",
        "hostname": "PC1",
        "interface": "Fa0",
        "expectedNetwork": "192.168.1.0",
        "expectedMask": "255.255.255.0"
      },
      {
        "id": "obj2",
        "type": "subnet",
        "desc": "PC2 IP is 192.168.1.20/24",
        "hostname": "PC2",
        "interface": "Fa0",
        "expectedNetwork": "192.168.1.0",
        "expectedMask": "255.255.255.0"
      },
      {
        "id": "obj3",
        "type": "ping",
        "desc": "PC1 → PC2 ping succeeds",
        "srcDeviceId": "pc-1",
        "dstIp": "192.168.1.20"
      }
    ],
    "hints": [
      "Click a PC to select it. Configure its interface in the right panel.",
      "Both PCs must be in the same /24 subnet (192.168.1.0/255.255.255.0).",
      "Click 'Test All Connections' to check your work."
    ],
    "topology": {
      "devices": [
        {
          "id": "pc-1",
          "type": "pc",
          "hostname": "PC1",
          "x": 280,
          "y": 300,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "",
              "subnetMask": "",
              "macAddress": "AA:BB:CC:00:00:01"
            }
          ],
          "config": {
            "defaultGateway": ""
          }
        },
        {
          "id": "sw-1",
          "type": "switch",
          "hostname": "SW1",
          "x": 520,
          "y": 300,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "pc-2",
          "type": "pc",
          "hostname": "PC2",
          "x": 760,
          "y": 300,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "",
              "subnetMask": "",
              "macAddress": "AA:BB:CC:00:00:02"
            }
          ],
          "config": {
            "defaultGateway": ""
          }
        }
      ],
      "links": [
        {
          "id": "link-1",
          "sourceDeviceId": "pc-1",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-1",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "link-2",
          "sourceDeviceId": "sw-1",
          "sourceInterface": "FastEthernet0/1",
          "destDeviceId": "pc-2",
          "destInterface": "FastEthernet0",
          "type": "ethernet",
          "status": "up"
        }
      ]
    }
  },
  {
    "id": 2,
    "title": "Subnetting Challenge",
    "topic": "Subnetting / VLSM",
    "description": "Divide the 192.168.10.0/24 address space into two equal /25 subnets. Assign one subnet to the left LAN and one to the right LAN. Use the Subnet Calculator (bottom right button) to help.",
    "ccnaRef": "CCNA ITN: Chapter 9 – Subnetting IP Networks",
    "sandboxMode": false,
    "objectives": [
      {
        "id": "obj1",
        "desc": "PC1 is in subnet 192.168.10.0/25"
      },
      {
        "id": "obj2",
        "desc": "PC2 is in subnet 192.168.10.128/25"
      },
      {
        "id": "obj3",
        "desc": "PC1 can ping PC1B (same subnet)"
      },
      {
        "id": "obj4",
        "desc": "PC2 can ping PC2B (same subnet)"
      }
    ],
    "requirements": [
      {
        "id": "obj1",
        "type": "subnet",
        "desc": "PC1 is in 192.168.10.0/25",
        "hostname": "PC1",
        "interface": "Fa0",
        "expectedNetwork": "192.168.10.0",
        "expectedMask": "255.255.255.128"
      },
      {
        "id": "obj2",
        "type": "subnet",
        "desc": "PC2 is in 192.168.10.128/25",
        "hostname": "PC2",
        "interface": "Fa0",
        "expectedNetwork": "192.168.10.128",
        "expectedMask": "255.255.255.128"
      },
      {
        "id": "obj3",
        "type": "ping",
        "desc": "PC1 → PC1B ping succeeds",
        "srcDeviceId": "pc-3",
        "dstIp": "192.168.10.2"
      },
      {
        "id": "obj4",
        "type": "ping",
        "desc": "PC2 → PC2B ping succeeds",
        "srcDeviceId": "pc-5",
        "dstIp": "192.168.10.130"
      }
    ],
    "hints": [
      "192.168.10.0/24 has 256 addresses. Splitting into /25 gives two blocks of 128.",
      "Subnet 1: 192.168.10.0 – 192.168.10.127  (mask: 255.255.255.128)",
      "Subnet 2: 192.168.10.128 – 192.168.10.255  (mask: 255.255.255.128)",
      "Use the Subnet Calculator button to verify your subnets."
    ],
    "topology": {
      "devices": [
        {
          "id": "pc-3",
          "type": "pc",
          "hostname": "PC1",
          "x": 160,
          "y": 280,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "",
              "subnetMask": "",
              "macAddress": "AA:BB:CC:01:00:01"
            }
          ],
          "config": {}
        },
        {
          "id": "pc-4",
          "type": "pc",
          "hostname": "PC1B",
          "x": 160,
          "y": 380,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.10.2",
              "subnetMask": "255.255.255.128",
              "macAddress": "AA:BB:CC:01:00:02"
            }
          ],
          "config": {}
        },
        {
          "id": "sw-2",
          "type": "switch",
          "hostname": "SW-Left",
          "x": 380,
          "y": 330,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "sw-3",
          "type": "switch",
          "hostname": "SW-Right",
          "x": 680,
          "y": 330,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "pc-5",
          "type": "pc",
          "hostname": "PC2",
          "x": 900,
          "y": 280,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "",
              "subnetMask": "",
              "macAddress": "AA:BB:CC:02:00:01"
            }
          ],
          "config": {}
        },
        {
          "id": "pc-6",
          "type": "pc",
          "hostname": "PC2B",
          "x": 900,
          "y": 380,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.10.130",
              "subnetMask": "255.255.255.128",
              "macAddress": "AA:BB:CC:02:00:02"
            }
          ],
          "config": {}
        }
      ],
      "links": [
        {
          "id": "l-1",
          "sourceDeviceId": "pc-3",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-2",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l-2",
          "sourceDeviceId": "pc-4",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-2",
          "destInterface": "FastEthernet0/1",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l-3",
          "sourceDeviceId": "pc-5",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-3",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l-4",
          "sourceDeviceId": "pc-6",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-3",
          "destInterface": "FastEthernet0/1",
          "type": "ethernet",
          "status": "up"
        }
      ]
    }
  },
  {
    "id": 3,
    "title": "Inter-VLAN Routing",
    "topic": "VLANs / Router-on-a-Stick",
    "description": "Configure two VLANs on the switch, assign PCs to VLANs, and use a Router-on-a-Stick configuration to allow inter-VLAN routing.",
    "ccnaRef": "CCNA SRWE: Chapter 4 – Inter-VLAN Routing",
    "sandboxMode": false,
    "objectives": [
      {
        "id": "obj1",
        "desc": "VLAN 10 (Sales) exists on SW1"
      },
      {
        "id": "obj2",
        "desc": "VLAN 20 (HR) exists on SW1"
      },
      {
        "id": "obj3",
        "desc": "PC1 (VLAN 10) can ping PC2 (VLAN 20) via R1"
      }
    ],
    "requirements": [
      {
        "id": "obj1",
        "type": "vlan",
        "desc": "VLAN 10 on SW1",
        "hostname": "SW1",
        "vlanId": 10
      },
      {
        "id": "obj2",
        "type": "vlan",
        "desc": "VLAN 20 on SW1",
        "hostname": "SW1",
        "vlanId": 20
      },
      {
        "id": "obj3",
        "type": "ping",
        "desc": "PC1 → PC2 inter-VLAN ping",
        "srcDeviceId": "pc-7",
        "dstIp": "192.168.20.10"
      }
    ],
    "hints": [
      "Configure VLAN 10 (Sales) and VLAN 20 (HR) on SW1 in the VLAN tab.",
      "Set PC1's port (Fa0/0) as Access VLAN 10, PC2's port (Fa0/1) as Access VLAN 20.",
      "Set the router port (Fa0/2) as Trunk.",
      "On R1: add sub-interfaces for each VLAN with encapsulation 802.1Q.",
      "R1 G0/0.10 → 192.168.10.1/24, R1 G0/0.20 → 192.168.20.1/24.",
      "Set each PC's gateway to its respective VLAN gateway IP."
    ],
    "topology": {
      "devices": [
        {
          "id": "pc-7",
          "type": "pc",
          "hostname": "PC1",
          "x": 160,
          "y": 240,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.10.10",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:03:00:01"
            }
          ],
          "config": {
            "defaultGateway": ""
          }
        },
        {
          "id": "pc-8",
          "type": "pc",
          "hostname": "PC2",
          "x": 160,
          "y": 380,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.20.10",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:03:00:02"
            }
          ],
          "config": {
            "defaultGateway": ""
          }
        },
        {
          "id": "sw-4",
          "type": "switch",
          "hostname": "SW1",
          "x": 460,
          "y": 310,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 10
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 20
            },
            {
              "name": "GigabitEthernet0/1",
              "shortName": "G0/1",
              "status": "up",
              "trunkMode": true,
              "allowedVlans": [
                10,
                20
              ]
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "r-1",
          "type": "router",
          "hostname": "R1",
          "x": 720,
          "y": 310,
          "interfaces": [
            {
              "name": "GigabitEthernet0/0",
              "shortName": "G0/0",
              "status": "up",
              "ipAddress": "",
              "subnetMask": ""
            },
            {
              "name": "GigabitEthernet0/1",
              "shortName": "G0/1",
              "status": "down",
              "ipAddress": "",
              "subnetMask": ""
            }
          ],
          "config": {}
        }
      ],
      "links": [
        {
          "id": "l-10",
          "sourceDeviceId": "pc-7",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-4",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l-11",
          "sourceDeviceId": "pc-8",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-4",
          "destInterface": "FastEthernet0/1",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l-12",
          "sourceDeviceId": "sw-4",
          "sourceInterface": "GigabitEthernet0/1",
          "destDeviceId": "r-1",
          "destInterface": "GigabitEthernet0/0",
          "type": "ethernet",
          "status": "up"
        }
      ]
    }
  },
  {
    "id": 4,
    "title": "DHCP Server Setup",
    "topic": "DHCP & Application Layer",
    "description": "A Server has been placed as the DHCP server. Configure a DHCP pool on it so that PC1 and PC2 automatically receive IP addresses. Then verify that both PCs can ping each other.",
    "ccnaRef": "CCNA ITN: Module 15 – IP Addressing Services",
    "sandboxMode": false,
    "objectives": [
      {
        "id": "obj1",
        "desc": "Server has a DHCP pool for 192.168.1.0/24"
      },
      {
        "id": "obj2",
        "desc": "PC1 receives an IP from DHCP (192.168.1.0/24)"
      },
      {
        "id": "obj3",
        "desc": "PC2 receives an IP from DHCP (192.168.1.0/24)"
      },
      {
        "id": "obj4",
        "desc": "PC1 can ping PC2"
      }
    ],
    "requirements": [
      {
        "id": "obj1",
        "type": "dhcp-pool",
        "desc": "DHCP pool on SRV1 covers 192.168.1.0/24",
        "hostname": "SRV1",
        "expectedNetwork": "192.168.1.0",
        "expectedMask": "255.255.255.0"
      },
      {
        "id": "obj2",
        "type": "subnet",
        "desc": "PC1 is in 192.168.1.0/24",
        "hostname": "PC1",
        "interface": "Fa0",
        "expectedNetwork": "192.168.1.0",
        "expectedMask": "255.255.255.0"
      },
      {
        "id": "obj3",
        "type": "subnet",
        "desc": "PC2 is in 192.168.1.0/24",
        "hostname": "PC2",
        "interface": "Fa0",
        "expectedNetwork": "192.168.1.0",
        "expectedMask": "255.255.255.0"
      },
      {
        "id": "obj4",
        "type": "ping",
        "desc": "PC1 → PC2 ping succeeds",
        "srcDeviceId": "pc-4a",
        "dstIp": "192.168.1.20"
      }
    ],
    "hints": [
      "Click on SRV1, then go to the Advanced tab to configure the DHCP pool.",
      "Set Network: 192.168.1.0, Start: 192.168.1.10, End: 192.168.1.100, Mask: 255.255.255.0",
      "After applying the DHCP pool, manually assign IPs to PC1 (192.168.1.10) and PC2 (192.168.1.20) to simulate DHCP lease — the game auto-validates the subnet membership.",
      "DHCP is an Application-Layer (L7) protocol that uses UDP port 67 (server) and 68 (client)."
    ],
    "topology": {
      "devices": [
        {
          "id": "srv-4",
          "type": "server",
          "hostname": "SRV1",
          "x": 520,
          "y": 200,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.1.1",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:04:00:01"
            }
          ],
          "config": {
            "defaultGateway": ""
          },
          "dhcpPool": null
        },
        {
          "id": "sw-4a",
          "type": "switch",
          "hostname": "SW1",
          "x": 520,
          "y": 320,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/2",
              "shortName": "Fa0/2",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "pc-4a",
          "type": "pc",
          "hostname": "PC1",
          "x": 300,
          "y": 420,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "",
              "subnetMask": "",
              "macAddress": "AA:BB:CC:04:00:02"
            }
          ],
          "config": {
            "defaultGateway": "192.168.1.1"
          }
        },
        {
          "id": "pc-4b",
          "type": "pc",
          "hostname": "PC2",
          "x": 740,
          "y": 420,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "",
              "subnetMask": "",
              "macAddress": "AA:BB:CC:04:00:03"
            }
          ],
          "config": {
            "defaultGateway": "192.168.1.1"
          }
        }
      ],
      "links": [
        {
          "id": "l4-1",
          "sourceDeviceId": "srv-4",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-4a",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l4-2",
          "sourceDeviceId": "pc-4a",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-4a",
          "destInterface": "FastEthernet0/1",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l4-3",
          "sourceDeviceId": "pc-4b",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-4a",
          "destInterface": "FastEthernet0/2",
          "type": "ethernet",
          "status": "up"
        }
      ]
    }
  },
  {
    "id": 5,
    "title": "WAN Static Routing",
    "topic": "WAN & Static Routes",
    "description": "Two LANs are separated by a point-to-point WAN link. Configure static routes on both routers so PCs on opposite sides can communicate. Use the Terminal: ip route <network> <mask> <next-hop>.",
    "ccnaRef": "CCNA ITN: Module 9 – Basic Router Configuration / Module 10 – IP Routing",
    "sandboxMode": false,
    "objectives": [
      {
        "id": "obj1",
        "desc": "R1 has a static route to 10.2.0.0/24"
      },
      {
        "id": "obj2",
        "desc": "R2 has a static route to 10.1.0.0/24"
      },
      {
        "id": "obj3",
        "desc": "PC1 can ping PC2 (10.2.0.10)"
      },
      {
        "id": "obj4",
        "desc": "PC2 can ping PC1 (10.1.0.10)"
      }
    ],
    "requirements": [
      {
        "id": "obj1",
        "type": "route-exists",
        "desc": "R1 has route to 10.2.0.0/24",
        "hostname": "R1",
        "network": "10.2.0.0",
        "mask": "255.255.255.0"
      },
      {
        "id": "obj2",
        "type": "route-exists",
        "desc": "R2 has route to 10.1.0.0/24",
        "hostname": "R2",
        "network": "10.1.0.0",
        "mask": "255.255.255.0"
      },
      {
        "id": "obj3",
        "type": "ping",
        "desc": "PC1 → PC2 cross-WAN ping",
        "srcDeviceId": "pc-5a",
        "dstIp": "10.2.0.10"
      },
      {
        "id": "obj4",
        "type": "ping",
        "desc": "PC2 → PC1 cross-WAN ping",
        "srcDeviceId": "pc-5b",
        "dstIp": "10.1.0.10"
      }
    ],
    "hints": [
      "Select R1 in the terminal. Run: enable → conf t → ip route 10.2.0.0 255.255.255.0 10.0.0.2",
      "Select R2 in the terminal. Run: enable → conf t → ip route 10.1.0.0 255.255.255.0 10.0.0.1",
      "The WAN link is 10.0.0.0/30. R1's WAN IP is 10.0.0.1; R2's is 10.0.0.2.",
      "Each PC needs its router as the default gateway. PC1 gateway = 10.1.0.1, PC2 gateway = 10.2.0.1.",
      "Verify with: show ip route (on each router)."
    ],
    "topology": {
      "devices": [
        {
          "id": "pc-5a",
          "type": "pc",
          "hostname": "PC1",
          "x": 120,
          "y": 320,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "10.1.0.10",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:05:00:01"
            }
          ],
          "config": {
            "defaultGateway": "10.1.0.1"
          }
        },
        {
          "id": "sw-5a",
          "type": "switch",
          "hostname": "SW-Left",
          "x": 300,
          "y": 320,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "r-5a",
          "type": "router",
          "hostname": "R1",
          "x": 490,
          "y": 320,
          "interfaces": [
            {
              "name": "GigabitEthernet0/0",
              "shortName": "G0/0",
              "status": "up",
              "ipAddress": "10.1.0.1",
              "subnetMask": "255.255.255.0"
            },
            {
              "name": "GigabitEthernet0/1",
              "shortName": "G0/1",
              "status": "up",
              "ipAddress": "10.0.0.1",
              "subnetMask": "255.255.255.252"
            }
          ],
          "config": {}
        },
        {
          "id": "r-5b",
          "type": "router",
          "hostname": "R2",
          "x": 680,
          "y": 320,
          "interfaces": [
            {
              "name": "GigabitEthernet0/0",
              "shortName": "G0/0",
              "status": "up",
              "ipAddress": "10.0.0.2",
              "subnetMask": "255.255.255.252"
            },
            {
              "name": "GigabitEthernet0/1",
              "shortName": "G0/1",
              "status": "up",
              "ipAddress": "10.2.0.1",
              "subnetMask": "255.255.255.0"
            }
          ],
          "config": {}
        },
        {
          "id": "sw-5b",
          "type": "switch",
          "hostname": "SW-Right",
          "x": 870,
          "y": 320,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "pc-5b",
          "type": "pc",
          "hostname": "PC2",
          "x": 1050,
          "y": 320,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "10.2.0.10",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:05:00:02"
            }
          ],
          "config": {
            "defaultGateway": "10.2.0.1"
          }
        }
      ],
      "links": [
        {
          "id": "l5-1",
          "sourceDeviceId": "pc-5a",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-5a",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l5-2",
          "sourceDeviceId": "sw-5a",
          "sourceInterface": "FastEthernet0/1",
          "destDeviceId": "r-5a",
          "destInterface": "GigabitEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l5-3",
          "sourceDeviceId": "r-5a",
          "sourceInterface": "GigabitEthernet0/1",
          "destDeviceId": "r-5b",
          "destInterface": "GigabitEthernet0/0",
          "type": "serial",
          "status": "up"
        },
        {
          "id": "l5-4",
          "sourceDeviceId": "r-5b",
          "sourceInterface": "GigabitEthernet0/1",
          "destDeviceId": "sw-5b",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l5-5",
          "sourceDeviceId": "sw-5b",
          "sourceInterface": "FastEthernet0/1",
          "destDeviceId": "pc-5b",
          "destInterface": "FastEthernet0",
          "type": "ethernet",
          "status": "up"
        }
      ]
    }
  },
  {
    "id": 6,
    "title": "Default Route to the Internet",
    "topic": "Default Routes & Internet Gateway",
    "description": "The edge router R1 connects your LAN to the Internet (Cloud). Add a default route on R1 pointing to the ISP gateway (203.0.113.1) so that PCs can reach the Internet. This is the 'gateway of last resort'.",
    "ccnaRef": "CCNA ITN: Module 10 – IP Routing Concepts",
    "sandboxMode": false,
    "objectives": [
      {
        "id": "obj1",
        "desc": "R1 has a default route (0.0.0.0/0) via 203.0.113.1"
      },
      {
        "id": "obj2",
        "desc": "PC1 can ping the Internet (8.8.8.8)"
      },
      {
        "id": "obj3",
        "desc": "PC2 can ping the Internet (8.8.8.8)"
      }
    ],
    "requirements": [
      {
        "id": "obj1",
        "type": "route-exists",
        "desc": "R1 default route exists",
        "hostname": "R1",
        "network": "0.0.0.0",
        "mask": "0.0.0.0"
      },
      {
        "id": "obj2",
        "type": "ping",
        "desc": "PC1 → Internet ping",
        "srcDeviceId": "pc-6a",
        "dstIp": "8.8.8.8"
      },
      {
        "id": "obj3",
        "type": "ping",
        "desc": "PC2 → Internet ping",
        "srcDeviceId": "pc-6b",
        "dstIp": "8.8.8.8"
      }
    ],
    "hints": [
      "Select R1 in the terminal. The command is: ip route 0.0.0.0 0.0.0.0 203.0.113.1",
      "A default route matches ANY destination not in the routing table — the 'catch-all'.",
      "The ISP side has IP 203.0.113.1. R1's WAN interface is 203.0.113.2.",
      "Verify with: show ip route — you should see a route marked 'S*' (static default).",
      "The Internet cloud device already has IP 8.8.8.8 for ping testing."
    ],
    "topology": {
      "devices": [
        {
          "id": "pc-6a",
          "type": "pc",
          "hostname": "PC1",
          "x": 140,
          "y": 280,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.1.10",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:06:00:01"
            }
          ],
          "config": {
            "defaultGateway": "192.168.1.1"
          }
        },
        {
          "id": "pc-6b",
          "type": "pc",
          "hostname": "PC2",
          "x": 140,
          "y": 380,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.1.20",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:06:00:02"
            }
          ],
          "config": {
            "defaultGateway": "192.168.1.1"
          }
        },
        {
          "id": "sw-6a",
          "type": "switch",
          "hostname": "SW1",
          "x": 340,
          "y": 330,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/2",
              "shortName": "Fa0/2",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "r-6a",
          "type": "router",
          "hostname": "R1",
          "x": 560,
          "y": 330,
          "interfaces": [
            {
              "name": "GigabitEthernet0/0",
              "shortName": "G0/0",
              "status": "up",
              "ipAddress": "192.168.1.1",
              "subnetMask": "255.255.255.0"
            },
            {
              "name": "GigabitEthernet0/1",
              "shortName": "G0/1",
              "status": "up",
              "ipAddress": "203.0.113.2",
              "subnetMask": "255.255.255.252"
            }
          ],
          "config": {}
        },
        {
          "id": "cloud-6",
          "type": "cloud",
          "hostname": "Internet",
          "x": 800,
          "y": 330,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "203.0.113.1",
              "subnetMask": "255.255.255.252",
              "macAddress": "AA:BB:CC:06:FF:01"
            },
            {
              "name": "FastEthernet1",
              "shortName": "Fa1",
              "status": "up",
              "ipAddress": "8.8.8.8",
              "subnetMask": "255.255.255.255",
              "macAddress": "AA:BB:CC:06:FF:02"
            }
          ],
          "config": {}
        }
      ],
      "links": [
        {
          "id": "l6-1",
          "sourceDeviceId": "pc-6a",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-6a",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l6-2",
          "sourceDeviceId": "pc-6b",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-6a",
          "destInterface": "FastEthernet0/1",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l6-3",
          "sourceDeviceId": "sw-6a",
          "sourceInterface": "FastEthernet0/2",
          "destDeviceId": "r-6a",
          "destInterface": "GigabitEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l6-4",
          "sourceDeviceId": "r-6a",
          "sourceInterface": "GigabitEthernet0/1",
          "destDeviceId": "cloud-6",
          "destInterface": "FastEthernet0",
          "type": "serial",
          "status": "up"
        }
      ]
    }
  },
  {
    "id": 7,
    "title": "OSI Model — Packet Trace",
    "topic": "OSI & TCP/IP Models",
    "description": "A network is already wired up and working. Your mission: use the Terminal to run 'ping' and 'traceroute', then use the Packet Inspector to observe which OSI layer each protocol header belongs to. Answer the layer-quiz objectives by configuring the correct interface IPs to match the expected OSI-layer mappings.",
    "ccnaRef": "CCNA ITN: Module 3 – Protocols and Models",
    "sandboxMode": false,
    "objectives": [
      {
        "id": "obj1",
        "desc": "PC1 can reach SRV1 (ping 172.16.1.100)"
      },
      {
        "id": "obj2",
        "desc": "R1 G0/0 is configured at the Network Layer (has an IP)"
      },
      {
        "id": "obj3",
        "desc": "SW1 operates at the Data Link Layer (no IP needed)"
      },
      {
        "id": "obj4",
        "desc": "PC1 → SRV1 traceroute completes (R1 appears as hop 1)"
      }
    ],
    "requirements": [
      {
        "id": "obj1",
        "type": "ping",
        "desc": "PC1 ping to SRV1 succeeds",
        "srcDeviceId": "pc-7a",
        "dstIp": "172.16.1.100"
      },
      {
        "id": "obj2",
        "type": "subnet",
        "desc": "R1 G0/0 has 172.16.0.1/24",
        "hostname": "R1",
        "interface": "G0/0",
        "expectedNetwork": "172.16.0.0",
        "expectedMask": "255.255.255.0"
      },
      {
        "id": "obj3",
        "type": "ping",
        "desc": "SW1 correctly forwards (no IP needed — Layer 2 device)",
        "srcDeviceId": "pc-7a",
        "dstIp": "172.16.0.1"
      },
      {
        "id": "obj4",
        "type": "ping",
        "desc": "PC1 can reach SRV1 via R1",
        "srcDeviceId": "pc-7a",
        "dstIp": "172.16.1.100"
      }
    ],
    "hints": [
      "The OSI model has 7 layers: L1=Physical, L2=Data Link, L3=Network, L4=Transport, L5-7=Upper Layers.",
      "Routers operate at Layer 3 (Network) — they forward packets using IP addresses.",
      "Switches operate at Layer 2 (Data Link) — they forward frames using MAC addresses.",
      "PCs are end devices spanning L1-L7.",
      "Configure R1 G0/0 with IP 172.16.0.1/24 and G0/1 with 172.16.1.1/24.",
      "Set PC1 gateway to 172.16.0.1 and SRV1 gateway to 172.16.1.1.",
      "Run traceroute 172.16.1.100 on PC1 to observe the L3 hop through R1."
    ],
    "topology": {
      "devices": [
        {
          "id": "pc-7a",
          "type": "pc",
          "hostname": "PC1",
          "x": 130,
          "y": 320,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "172.16.0.10",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:07:00:01"
            }
          ],
          "config": {
            "defaultGateway": "172.16.0.1"
          }
        },
        {
          "id": "sw-7a",
          "type": "switch",
          "hostname": "SW1",
          "x": 330,
          "y": 320,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "r-7a",
          "type": "router",
          "hostname": "R1",
          "x": 550,
          "y": 320,
          "interfaces": [
            {
              "name": "GigabitEthernet0/0",
              "shortName": "G0/0",
              "status": "up",
              "ipAddress": "",
              "subnetMask": ""
            },
            {
              "name": "GigabitEthernet0/1",
              "shortName": "G0/1",
              "status": "up",
              "ipAddress": "172.16.1.1",
              "subnetMask": "255.255.255.0"
            }
          ],
          "config": {}
        },
        {
          "id": "sw-7b",
          "type": "switch",
          "hostname": "SW2",
          "x": 750,
          "y": 320,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "srv-7",
          "type": "server",
          "hostname": "SRV1",
          "x": 950,
          "y": 320,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "172.16.1.100",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:07:00:FF"
            }
          ],
          "config": {
            "defaultGateway": "172.16.1.1"
          }
        }
      ],
      "links": [
        {
          "id": "l7-1",
          "sourceDeviceId": "pc-7a",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-7a",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l7-2",
          "sourceDeviceId": "sw-7a",
          "sourceInterface": "FastEthernet0/1",
          "destDeviceId": "r-7a",
          "destInterface": "GigabitEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l7-3",
          "sourceDeviceId": "r-7a",
          "sourceInterface": "GigabitEthernet0/1",
          "destDeviceId": "sw-7b",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l7-4",
          "sourceDeviceId": "sw-7b",
          "sourceInterface": "FastEthernet0/1",
          "destDeviceId": "srv-7",
          "destInterface": "FastEthernet0",
          "type": "ethernet",
          "status": "up"
        }
      ]
    }
  },
  {
    "id": 8,
    "title": "Ethernet Frames & MAC Addresses",
    "topic": "Data Link Layer / MAC Addressing",
    "description": "Switches learn MAC addresses dynamically. In this lab, send packets between PCs to populate the MAC address tables, then use 'show mac address-table' on SW1 to verify the entries. Finally, wire everything correctly so PC1 can ping all hosts.",
    "ccnaRef": "CCNA ITN: Modules 4–7 – Physical & Data Link Layers",
    "sandboxMode": false,
    "objectives": [
      {
        "id": "obj1",
        "desc": "PC1 can ping PC2 (192.168.10.20)"
      },
      {
        "id": "obj2",
        "desc": "PC1 can ping PC3 (192.168.10.30)"
      },
      {
        "id": "obj3",
        "desc": "PC1 can ping PC4 (192.168.10.40)"
      },
      {
        "id": "obj4",
        "desc": "SW1 MAC table is populated (run ping first, then show mac address-table)"
      }
    ],
    "requirements": [
      {
        "id": "obj1",
        "type": "ping",
        "desc": "PC1 → PC2",
        "srcDeviceId": "pc-8a",
        "dstIp": "192.168.10.20"
      },
      {
        "id": "obj2",
        "type": "ping",
        "desc": "PC1 → PC3",
        "srcDeviceId": "pc-8a",
        "dstIp": "192.168.10.30"
      },
      {
        "id": "obj3",
        "type": "ping",
        "desc": "PC1 → PC4",
        "srcDeviceId": "pc-8a",
        "dstIp": "192.168.10.40"
      },
      {
        "id": "obj4",
        "type": "subnet",
        "desc": "PC1 correctly in 192.168.10.0/24",
        "hostname": "PC1",
        "interface": "Fa0",
        "expectedNetwork": "192.168.10.0",
        "expectedMask": "255.255.255.0"
      }
    ],
    "hints": [
      "A switch builds its MAC table by inspecting source MAC addresses of incoming frames.",
      "Hex: 0-9 then A-F. Each hex digit represents 4 bits. FF = 11111111 = 255 in decimal.",
      "MAC addresses are 48 bits (6 bytes) written as XX:XX:XX:XX:XX:XX in hex.",
      "Select SW1 and run: show mac address-table (after pinging to populate it).",
      "All PCs are already wired — just make sure PC1 has the correct IP: 192.168.10.10/24."
    ],
    "topology": {
      "devices": [
        {
          "id": "pc-8a",
          "type": "pc",
          "hostname": "PC1",
          "x": 150,
          "y": 200,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "",
              "subnetMask": "",
              "macAddress": "AA:BB:CC:08:00:01"
            }
          ],
          "config": {
            "defaultGateway": ""
          }
        },
        {
          "id": "pc-8b",
          "type": "pc",
          "hostname": "PC2",
          "x": 700,
          "y": 130,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.10.20",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:08:00:02"
            }
          ],
          "config": {
            "defaultGateway": ""
          }
        },
        {
          "id": "pc-8c",
          "type": "pc",
          "hostname": "PC3",
          "x": 700,
          "y": 260,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.10.30",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:08:00:03"
            }
          ],
          "config": {
            "defaultGateway": ""
          }
        },
        {
          "id": "pc-8d",
          "type": "pc",
          "hostname": "PC4",
          "x": 700,
          "y": 390,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.10.40",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:08:00:04"
            }
          ],
          "config": {
            "defaultGateway": ""
          }
        },
        {
          "id": "sw-8a",
          "type": "switch",
          "hostname": "SW1",
          "x": 440,
          "y": 290,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/2",
              "shortName": "Fa0/2",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/3",
              "shortName": "Fa0/3",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        }
      ],
      "links": [
        {
          "id": "l8-1",
          "sourceDeviceId": "pc-8a",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-8a",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l8-2",
          "sourceDeviceId": "pc-8b",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-8a",
          "destInterface": "FastEthernet0/1",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l8-3",
          "sourceDeviceId": "pc-8c",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-8a",
          "destInterface": "FastEthernet0/2",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l8-4",
          "sourceDeviceId": "pc-8d",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-8a",
          "destInterface": "FastEthernet0/3",
          "type": "ethernet",
          "status": "up"
        }
      ]
    }
  },
  {
    "id": 9,
    "title": "IPv4 Addressing Deep Dive",
    "topic": "IPv4 Unicast / Multicast / Broadcast",
    "description": "Three departments share a router. Each has its own /26 subnet carved from 192.168.50.0/24. Assign the correct first-usable IP to each router sub-interface and verify all three department PCs can ping the router gateway.",
    "ccnaRef": "CCNA ITN: Modules 11–12 – IPv4 Addressing",
    "sandboxMode": false,
    "objectives": [
      {
        "id": "obj1",
        "desc": "Dept-A PC can ping its gateway (192.168.50.1)"
      },
      {
        "id": "obj2",
        "desc": "Dept-B PC can ping its gateway (192.168.50.65)"
      },
      {
        "id": "obj3",
        "desc": "Dept-C PC can ping its gateway (192.168.50.129)"
      },
      {
        "id": "obj4",
        "desc": "R1 G0/0 is in 192.168.50.0/26"
      },
      {
        "id": "obj5",
        "desc": "R1 G0/1 is in 192.168.50.64/26"
      },
      {
        "id": "obj6",
        "desc": "R1 G0/2 is in 192.168.50.128/26"
      }
    ],
    "requirements": [
      {
        "id": "obj1",
        "type": "ping",
        "desc": "Dept-A → gateway",
        "srcDeviceId": "pc-9a",
        "dstIp": "192.168.50.1"
      },
      {
        "id": "obj2",
        "type": "ping",
        "desc": "Dept-B → gateway",
        "srcDeviceId": "pc-9b",
        "dstIp": "192.168.50.65"
      },
      {
        "id": "obj3",
        "type": "ping",
        "desc": "Dept-C → gateway",
        "srcDeviceId": "pc-9c",
        "dstIp": "192.168.50.129"
      },
      {
        "id": "obj4",
        "type": "subnet",
        "desc": "R1 G0/0 in .0/26",
        "hostname": "R1",
        "interface": "G0/0",
        "expectedNetwork": "192.168.50.0",
        "expectedMask": "255.255.255.192"
      },
      {
        "id": "obj5",
        "type": "subnet",
        "desc": "R1 G0/1 in .64/26",
        "hostname": "R1",
        "interface": "G0/1",
        "expectedNetwork": "192.168.50.64",
        "expectedMask": "255.255.255.192"
      },
      {
        "id": "obj6",
        "type": "subnet",
        "desc": "R1 G0/2 in .128/26",
        "hostname": "R1",
        "interface": "G0/2",
        "expectedNetwork": "192.168.50.128",
        "expectedMask": "255.255.255.192"
      }
    ],
    "hints": [
      "192.168.50.0/26 gives 4 subnets of 64 IPs each (62 usable hosts). Increment by 64.",
      "Subnet A: 192.168.50.0–63  → gateway 192.168.50.1  mask 255.255.255.192",
      "Subnet B: 192.168.50.64–127 → gateway 192.168.50.65 mask 255.255.255.192",
      "Subnet C: 192.168.50.128–191 → gateway 192.168.50.129 mask 255.255.255.192",
      "Select R1 in the terminal: enable → conf t → int g0/0 → ip address 192.168.50.1 255.255.255.192 → no shut",
      "Repeat for G0/1 and G0/2 with the respective subnet gateways."
    ],
    "topology": {
      "devices": [
        {
          "id": "r-9a",
          "type": "router",
          "hostname": "R1",
          "x": 540,
          "y": 310,
          "interfaces": [
            {
              "name": "GigabitEthernet0/0",
              "shortName": "G0/0",
              "status": "up",
              "ipAddress": "",
              "subnetMask": ""
            },
            {
              "name": "GigabitEthernet0/1",
              "shortName": "G0/1",
              "status": "up",
              "ipAddress": "",
              "subnetMask": ""
            },
            {
              "name": "GigabitEthernet0/2",
              "shortName": "G0/2",
              "status": "up",
              "ipAddress": "",
              "subnetMask": ""
            }
          ],
          "config": {}
        },
        {
          "id": "sw-9a",
          "type": "switch",
          "hostname": "SW-A",
          "x": 280,
          "y": 190,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "sw-9b",
          "type": "switch",
          "hostname": "SW-B",
          "x": 280,
          "y": 310,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "sw-9c",
          "type": "switch",
          "hostname": "SW-C",
          "x": 280,
          "y": 430,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "pc-9a",
          "type": "pc",
          "hostname": "DeptA-PC",
          "x": 80,
          "y": 190,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.50.10",
              "subnetMask": "255.255.255.192",
              "macAddress": "AA:BB:CC:09:00:01"
            }
          ],
          "config": {
            "defaultGateway": "192.168.50.1"
          }
        },
        {
          "id": "pc-9b",
          "type": "pc",
          "hostname": "DeptB-PC",
          "x": 80,
          "y": 310,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.50.74",
              "subnetMask": "255.255.255.192",
              "macAddress": "AA:BB:CC:09:00:02"
            }
          ],
          "config": {
            "defaultGateway": "192.168.50.65"
          }
        },
        {
          "id": "pc-9c",
          "type": "pc",
          "hostname": "DeptC-PC",
          "x": 80,
          "y": 430,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.50.138",
              "subnetMask": "255.255.255.192",
              "macAddress": "AA:BB:CC:09:00:03"
            }
          ],
          "config": {
            "defaultGateway": "192.168.50.129"
          }
        }
      ],
      "links": [
        {
          "id": "l9-1",
          "sourceDeviceId": "pc-9a",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-9a",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l9-2",
          "sourceDeviceId": "sw-9a",
          "sourceInterface": "FastEthernet0/1",
          "destDeviceId": "r-9a",
          "destInterface": "GigabitEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l9-3",
          "sourceDeviceId": "pc-9b",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-9b",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l9-4",
          "sourceDeviceId": "sw-9b",
          "sourceInterface": "FastEthernet0/1",
          "destDeviceId": "r-9a",
          "destInterface": "GigabitEthernet0/1",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l9-5",
          "sourceDeviceId": "pc-9c",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-9c",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l9-6",
          "sourceDeviceId": "sw-9c",
          "sourceInterface": "FastEthernet0/1",
          "destDeviceId": "r-9a",
          "destInterface": "GigabitEthernet0/2",
          "type": "ethernet",
          "status": "up"
        }
      ]
    }
  },
  {
    "id": 10,
    "title": "IPv6 Addressing",
    "topic": "IPv6 GUA & LLA",
    "description": "Configure IPv6 Global Unicast Addresses (GUA) on PC1 and PC2. PC1 gets 2001:db8:acad:1::10/64 and PC2 gets 2001:db8:acad:1::20/64. The switch handles Layer 2. Verify connectivity with a ping.",
    "ccnaRef": "CCNA ITN: Module 12 – IPv6 Addressing",
    "sandboxMode": false,
    "objectives": [
      {
        "id": "obj1",
        "desc": "PC1 has IPv6 GUA 2001:db8:acad:1::10/64"
      },
      {
        "id": "obj2",
        "desc": "PC2 has IPv6 GUA 2001:db8:acad:1::20/64"
      },
      {
        "id": "obj3",
        "desc": "PC1 can ping PC2 via IPv6"
      }
    ],
    "requirements": [
      {
        "id": "obj1",
        "type": "ipv6-address",
        "desc": "PC1 IPv6 GUA assigned",
        "hostname": "PC1",
        "interface": "Fa0",
        "expectedIPv6": "2001:db8:acad:1::10",
        "expectedPrefix": 64
      },
      {
        "id": "obj2",
        "type": "ipv6-address",
        "desc": "PC2 IPv6 GUA assigned",
        "hostname": "PC2",
        "interface": "Fa0",
        "expectedIPv6": "2001:db8:acad:1::20",
        "expectedPrefix": 64
      },
      {
        "id": "obj3",
        "type": "ping",
        "desc": "PC1 → PC2 IPv6 ping",
        "srcDeviceId": "pc-10a",
        "dstIp": "2001:db8:acad:1::20"
      }
    ],
    "hints": [
      "IPv6 addresses are 128 bits written as 8 groups of 4 hex digits, separated by colons.",
      "GUA (Global Unicast Address) starts with 2000::/3 — the most common routable range.",
      "LLA (Link-Local Address) starts with FE80::/10 and is auto-configured.",
      "In the terminal: ipv6 address 2001:db8:acad:1::10/64",
      "The /64 prefix means the first 64 bits are the network (2001:db8:acad:1) and the last 64 bits are the host (::10).",
      "Run: ping 2001:db8:acad:1::20 from PC1 to verify."
    ],
    "topology": {
      "devices": [
        {
          "id": "pc-10a",
          "type": "pc",
          "hostname": "PC1",
          "x": 220,
          "y": 300,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "",
              "subnetMask": "",
              "ipv6Address": "",
              "ipv6Prefix": 64,
              "macAddress": "AA:BB:CC:0A:00:01"
            }
          ],
          "config": {}
        },
        {
          "id": "sw-10a",
          "type": "switch",
          "hostname": "SW1",
          "x": 520,
          "y": 300,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "pc-10b",
          "type": "pc",
          "hostname": "PC2",
          "x": 820,
          "y": 300,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "",
              "subnetMask": "",
              "ipv6Address": "",
              "ipv6Prefix": 64,
              "macAddress": "AA:BB:CC:0A:00:02"
            }
          ],
          "config": {}
        }
      ],
      "links": [
        {
          "id": "l10-1",
          "sourceDeviceId": "pc-10a",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-10a",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l10-2",
          "sourceDeviceId": "pc-10b",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-10a",
          "destInterface": "FastEthernet0/1",
          "type": "ethernet",
          "status": "up"
        }
      ]
    }
  },
  {
    "id": 11,
    "title": "VLSM Network Design",
    "topic": "VLSM / Variable Length Subnet Masking",
    "description": "You have been given 10.0.0.0/22 (1022 usable hosts). Design a VLSM scheme for 4 departments: Engineering (250 hosts), Sales (60 hosts), HR (28 hosts), and the WAN link (2 hosts). Assign the correct subnets to each router interface.",
    "ccnaRef": "CCNA ITN: Module 11–12 – VLSM",
    "sandboxMode": false,
    "objectives": [
      {
        "id": "obj1",
        "desc": "R1 G0/0 in Engineering subnet 10.0.0.0/24 (250 hosts)"
      },
      {
        "id": "obj2",
        "desc": "R1 G0/1 in Sales subnet 10.0.1.0/26 (60 hosts)"
      },
      {
        "id": "obj3",
        "desc": "R1 G0/2 in HR subnet 10.0.1.64/27 (28 hosts)"
      },
      {
        "id": "obj4",
        "desc": "All department PCs can ping R1"
      }
    ],
    "requirements": [
      {
        "id": "obj1",
        "type": "subnet",
        "desc": "R1 G0/0 in Engineering /24",
        "hostname": "R1",
        "interface": "G0/0",
        "expectedNetwork": "10.0.0.0",
        "expectedMask": "255.255.255.0"
      },
      {
        "id": "obj2",
        "type": "subnet",
        "desc": "R1 G0/1 in Sales /26",
        "hostname": "R1",
        "interface": "G0/1",
        "expectedNetwork": "10.0.1.0",
        "expectedMask": "255.255.255.192"
      },
      {
        "id": "obj3",
        "type": "subnet",
        "desc": "R1 G0/2 in HR /27",
        "hostname": "R1",
        "interface": "G0/2",
        "expectedNetwork": "10.0.1.64",
        "expectedMask": "255.255.255.224"
      },
      {
        "id": "obj4",
        "type": "ping",
        "desc": "Eng-PC → R1 G0/0",
        "srcDeviceId": "pc-11a",
        "dstIp": "10.0.0.1"
      }
    ],
    "hints": [
      "VLSM = allocate the LARGEST subnet first, then carve smaller ones from remaining space.",
      "Engineering (250 hosts): need /24 → 10.0.0.0/24 (254 usable). Assign R1 G0/0 = 10.0.0.1/24",
      "Sales (60 hosts): need /26 (62 usable) → 10.0.1.0/26. Assign R1 G0/1 = 10.0.1.1/26",
      "HR (28 hosts): need /27 (30 usable) → 10.0.1.64/27. Assign R1 G0/2 = 10.0.1.65/27",
      "WAN link (2 hosts): need /30 → 10.0.1.96/30.",
      "Click the '÷ Subnet & VLSM Hub' button in the bottom right to practice VLSM scenario tables and verify subnets anytime!",
      "Configure with: int g0/0 → ip address 10.0.0.1 255.255.255.0"
    ],
    "topology": {
      "devices": [
        {
          "id": "r-11a",
          "type": "router",
          "hostname": "R1",
          "x": 540,
          "y": 310,
          "interfaces": [
            {
              "name": "GigabitEthernet0/0",
              "shortName": "G0/0",
              "status": "up",
              "ipAddress": "",
              "subnetMask": ""
            },
            {
              "name": "GigabitEthernet0/1",
              "shortName": "G0/1",
              "status": "up",
              "ipAddress": "",
              "subnetMask": ""
            },
            {
              "name": "GigabitEthernet0/2",
              "shortName": "G0/2",
              "status": "up",
              "ipAddress": "",
              "subnetMask": ""
            }
          ],
          "config": {}
        },
        {
          "id": "sw-11a",
          "type": "switch",
          "hostname": "SW-Eng",
          "x": 280,
          "y": 180,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "sw-11b",
          "type": "switch",
          "hostname": "SW-Sales",
          "x": 280,
          "y": 310,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "sw-11c",
          "type": "switch",
          "hostname": "SW-HR",
          "x": 280,
          "y": 440,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "pc-11a",
          "type": "pc",
          "hostname": "Eng-PC",
          "x": 80,
          "y": 180,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "10.0.0.10",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:0B:00:01"
            }
          ],
          "config": {
            "defaultGateway": "10.0.0.1"
          }
        },
        {
          "id": "pc-11b",
          "type": "pc",
          "hostname": "Sales-PC",
          "x": 80,
          "y": 310,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "10.0.1.10",
              "subnetMask": "255.255.255.192",
              "macAddress": "AA:BB:CC:0B:00:02"
            }
          ],
          "config": {
            "defaultGateway": "10.0.1.1"
          }
        },
        {
          "id": "pc-11c",
          "type": "pc",
          "hostname": "HR-PC",
          "x": 80,
          "y": 440,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "10.0.1.74",
              "subnetMask": "255.255.255.224",
              "macAddress": "AA:BB:CC:0B:00:03"
            }
          ],
          "config": {
            "defaultGateway": "10.0.1.65"
          }
        }
      ],
      "links": [
        {
          "id": "l11-1",
          "sourceDeviceId": "pc-11a",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-11a",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l11-2",
          "sourceDeviceId": "sw-11a",
          "sourceInterface": "FastEthernet0/1",
          "destDeviceId": "r-11a",
          "destInterface": "GigabitEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l11-3",
          "sourceDeviceId": "pc-11b",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-11b",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l11-4",
          "sourceDeviceId": "sw-11b",
          "sourceInterface": "FastEthernet0/1",
          "destDeviceId": "r-11a",
          "destInterface": "GigabitEthernet0/1",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l11-5",
          "sourceDeviceId": "pc-11c",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-11c",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l11-6",
          "sourceDeviceId": "sw-11c",
          "sourceInterface": "FastEthernet0/1",
          "destDeviceId": "r-11a",
          "destInterface": "GigabitEthernet0/2",
          "type": "ethernet",
          "status": "up"
        }
      ]
    }
  },
  {
    "id": 12,
    "title": "ICMP Ping & Traceroute",
    "topic": "ICMP / Upper Layers",
    "description": "The network has a broken hop — one router interface is misconfigured. Use 'ping' and 'traceroute' to locate the fault, fix it, and restore full end-to-end connectivity across the 3-router chain.",
    "ccnaRef": "CCNA ITN: Module 13 – ICMP",
    "sandboxMode": false,
    "objectives": [
      {
        "id": "obj1",
        "desc": "PC1 traceroute to 10.3.0.10 shows all 3 hops"
      },
      {
        "id": "obj2",
        "desc": "R2 G0/1 has correct IP 10.2.0.2/30"
      },
      {
        "id": "obj3",
        "desc": "R3 has route to 10.1.0.0/24 via 10.2.0.1"
      },
      {
        "id": "obj4",
        "desc": "PC1 can ping PC-Remote (10.3.0.10)"
      }
    ],
    "requirements": [
      {
        "id": "obj1",
        "type": "ping",
        "desc": "PC1 → 10.2.0.2 (R2 G0/0)",
        "srcDeviceId": "pc-12a",
        "dstIp": "10.2.0.2"
      },
      {
        "id": "obj2",
        "type": "subnet",
        "desc": "R2 G0/1 in 10.2.0.0/30",
        "hostname": "R2",
        "interface": "G0/1",
        "expectedNetwork": "10.2.0.0",
        "expectedMask": "255.255.255.252"
      },
      {
        "id": "obj3",
        "type": "route-exists",
        "desc": "R3 has route to 10.1.0.0/24",
        "hostname": "R3",
        "network": "10.1.0.0",
        "mask": "255.255.255.0"
      },
      {
        "id": "obj4",
        "type": "ping",
        "desc": "PC1 → PC-Remote full path",
        "srcDeviceId": "pc-12a",
        "dstIp": "10.3.0.10"
      }
    ],
    "hints": [
      "Run traceroute 10.3.0.10 on PC1 to see where it fails.",
      "ICMP uses the Network Layer (L3) — no ports, just echo request/reply.",
      "Check R2's interfaces: G0/0 should be 10.1.0.2/30, G0/1 should be 10.2.0.2/30 — one is wrong!",
      "Fix R2's broken interface, then add static routes so R1 and R3 can forward traffic.",
      "R1 needs: ip route 10.3.0.0 255.255.255.0 10.1.0.2",
      "R3 needs: ip route 10.1.0.0 255.255.255.0 10.2.0.1"
    ],
    "topology": {
      "devices": [
        {
          "id": "pc-12a",
          "type": "pc",
          "hostname": "PC1",
          "x": 80,
          "y": 310,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.1.10",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:0C:00:01"
            }
          ],
          "config": {
            "defaultGateway": "192.168.1.1"
          }
        },
        {
          "id": "r-12a",
          "type": "router",
          "hostname": "R1",
          "x": 280,
          "y": 310,
          "interfaces": [
            {
              "name": "GigabitEthernet0/0",
              "shortName": "G0/0",
              "status": "up",
              "ipAddress": "192.168.1.1",
              "subnetMask": "255.255.255.0"
            },
            {
              "name": "GigabitEthernet0/1",
              "shortName": "G0/1",
              "status": "up",
              "ipAddress": "10.1.0.1",
              "subnetMask": "255.255.255.252"
            }
          ],
          "config": {}
        },
        {
          "id": "r-12b",
          "type": "router",
          "hostname": "R2",
          "x": 540,
          "y": 310,
          "interfaces": [
            {
              "name": "GigabitEthernet0/0",
              "shortName": "G0/0",
              "status": "up",
              "ipAddress": "10.1.0.2",
              "subnetMask": "255.255.255.252"
            },
            {
              "name": "GigabitEthernet0/1",
              "shortName": "G0/1",
              "status": "up",
              "ipAddress": "10.99.99.2",
              "subnetMask": "255.255.255.252"
            }
          ],
          "config": {}
        },
        {
          "id": "r-12c",
          "type": "router",
          "hostname": "R3",
          "x": 800,
          "y": 310,
          "interfaces": [
            {
              "name": "GigabitEthernet0/0",
              "shortName": "G0/0",
              "status": "up",
              "ipAddress": "10.2.0.1",
              "subnetMask": "255.255.255.252"
            },
            {
              "name": "GigabitEthernet0/1",
              "shortName": "G0/1",
              "status": "up",
              "ipAddress": "10.3.0.1",
              "subnetMask": "255.255.255.0"
            }
          ],
          "config": {}
        },
        {
          "id": "pc-12b",
          "type": "pc",
          "hostname": "PC-Remote",
          "x": 1000,
          "y": 310,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "10.3.0.10",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:0C:00:02"
            }
          ],
          "config": {
            "defaultGateway": "10.3.0.1"
          }
        }
      ],
      "links": [
        {
          "id": "l12-1",
          "sourceDeviceId": "pc-12a",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "r-12a",
          "destInterface": "GigabitEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l12-2",
          "sourceDeviceId": "r-12a",
          "sourceInterface": "GigabitEthernet0/1",
          "destDeviceId": "r-12b",
          "destInterface": "GigabitEthernet0/0",
          "type": "serial",
          "status": "up"
        },
        {
          "id": "l12-3",
          "sourceDeviceId": "r-12b",
          "sourceInterface": "GigabitEthernet0/1",
          "destDeviceId": "r-12c",
          "destInterface": "GigabitEthernet0/0",
          "type": "serial",
          "status": "up"
        },
        {
          "id": "l12-4",
          "sourceDeviceId": "r-12c",
          "sourceInterface": "GigabitEthernet0/1",
          "destDeviceId": "pc-12b",
          "destInterface": "FastEthernet0",
          "type": "ethernet",
          "status": "up"
        }
      ]
    }
  },
  {
    "id": 13,
    "title": "TCP & UDP Transport Layer",
    "topic": "TCP/UDP / Transport Layer",
    "description": "Configure a server with the correct services running on standard TCP/UDP ports. Use the Packet Inspector to send TCP and UDP packets, observe the port numbers, and verify connectivity to each service port.",
    "ccnaRef": "CCNA ITN: Module 14 – Transport Layer",
    "sandboxMode": false,
    "objectives": [
      {
        "id": "obj1",
        "desc": "PC1 can reach SRV1 via TCP (send a TCP packet in the Packet Inspector)"
      },
      {
        "id": "obj2",
        "desc": "PC1 can reach SRV1 via UDP (send a UDP packet in the Packet Inspector)"
      },
      {
        "id": "obj3",
        "desc": "PC1 can ping SRV1 (192.168.1.100)"
      },
      {
        "id": "obj4",
        "desc": "SRV1 is in the correct subnet 192.168.1.0/24"
      }
    ],
    "requirements": [
      {
        "id": "obj1",
        "type": "ping",
        "desc": "PC1 → SRV1 TCP-style ping",
        "srcDeviceId": "pc-13a",
        "dstIp": "192.168.1.100"
      },
      {
        "id": "obj2",
        "type": "ping",
        "desc": "PC1 → SRV1 UDP-style ping",
        "srcDeviceId": "pc-13a",
        "dstIp": "192.168.1.100"
      },
      {
        "id": "obj3",
        "type": "ping",
        "desc": "PC1 → SRV1 ICMP ping succeeds",
        "srcDeviceId": "pc-13a",
        "dstIp": "192.168.1.100"
      },
      {
        "id": "obj4",
        "type": "subnet",
        "desc": "SRV1 is in 192.168.1.0/24",
        "hostname": "SRV1",
        "interface": "Fa0",
        "expectedNetwork": "192.168.1.0",
        "expectedMask": "255.255.255.0"
      }
    ],
    "hints": [
      "TCP (Transmission Control Protocol) is connection-oriented: SYN → SYN-ACK → ACK (3-way handshake).",
      "UDP (User Datagram Protocol) is connectionless and faster — no handshake.",
      "Well-known TCP ports: HTTP=80, HTTPS=443, FTP=21, SSH=22, Telnet=23.",
      "Well-known UDP ports: DNS=53, DHCP=67/68, TFTP=69, SNMP=161.",
      "Use the Packet Inspector (bottom-right) to send TCP and UDP packets to 192.168.1.100.",
      "SRV1 needs IP 192.168.1.100/24. Assign it via the device panel or terminal."
    ],
    "topology": {
      "devices": [
        {
          "id": "pc-13a",
          "type": "pc",
          "hostname": "PC1",
          "x": 180,
          "y": 300,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.1.10",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:0D:00:01"
            }
          ],
          "config": {
            "defaultGateway": "192.168.1.1"
          }
        },
        {
          "id": "pc-13b",
          "type": "pc",
          "hostname": "PC2",
          "x": 180,
          "y": 420,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "192.168.1.20",
              "subnetMask": "255.255.255.0",
              "macAddress": "AA:BB:CC:0D:00:02"
            }
          ],
          "config": {
            "defaultGateway": "192.168.1.1"
          }
        },
        {
          "id": "sw-13a",
          "type": "switch",
          "hostname": "SW1",
          "x": 450,
          "y": 360,
          "interfaces": [
            {
              "name": "FastEthernet0/0",
              "shortName": "Fa0/0",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/1",
              "shortName": "Fa0/1",
              "status": "up",
              "vlanId": 1
            },
            {
              "name": "FastEthernet0/2",
              "shortName": "Fa0/2",
              "status": "up",
              "vlanId": 1
            }
          ],
          "vlans": [
            {
              "id": 1,
              "name": "default"
            }
          ],
          "config": {}
        },
        {
          "id": "srv-13",
          "type": "server",
          "hostname": "SRV1",
          "x": 730,
          "y": 300,
          "interfaces": [
            {
              "name": "FastEthernet0",
              "shortName": "Fa0",
              "status": "up",
              "ipAddress": "",
              "subnetMask": "",
              "macAddress": "AA:BB:CC:0D:00:FF"
            }
          ],
          "config": {
            "defaultGateway": "192.168.1.1"
          }
        }
      ],
      "links": [
        {
          "id": "l13-1",
          "sourceDeviceId": "pc-13a",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-13a",
          "destInterface": "FastEthernet0/0",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l13-2",
          "sourceDeviceId": "pc-13b",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-13a",
          "destInterface": "FastEthernet0/1",
          "type": "ethernet",
          "status": "up"
        },
        {
          "id": "l13-3",
          "sourceDeviceId": "srv-13",
          "sourceInterface": "FastEthernet0",
          "destDeviceId": "sw-13a",
          "destInterface": "FastEthernet0/2",
          "type": "ethernet",
          "status": "up"
        }
      ]
    }
  }
];
