const fs = require('fs');
const path = require('path');

const levelsDir = path.join(__dirname, '..', 'src', 'levels');
const outputFile = path.join(levelsDir, 'levelsData.js');

const files = fs.readdirSync(levelsDir).filter(f => f.startsWith('level_') && f.endsWith('.json')).sort();

const levels = [];
for (const file of files) {
  const content = fs.readFileSync(path.join(levelsDir, file), 'utf8');
  levels.push(JSON.parse(content));
}

const jsContent = `// src/levels/levelsData.js
// Autogenerated from level JSON files for cross-environment ES module compatibility.

export const LEVELS = ${JSON.stringify(levels, null, 2)};
`;

fs.writeFileSync(outputFile, jsContent, 'utf8');
console.log('Successfully built levelsData.js from ' + files.length + ' JSON files.');
